name: dariolab

include:
  - compose/compose.caddy.yml
  - compose/compose.watchtower.yml
  - compose/compose.portainer.yml
  - compose/compose.gateway.yml
  - compose/compose.apps.yml
  - compose/compose.fail2ban.yml
  - compose/compose.observability.yml
  - compose/compose.matrix.yml

networks:
  backend:
    driver: bridge
  wordle_duel_service_internal:
    internal: true

volumes:
  caddy_data:
  caddy_config:
  portainer_data:
  loki_data:
  grafana_data:
  geoipupdate_data:
  prometheus_data:
  alloy_data:
  conduit-data:
  wordle_duel_service_redis_data:
