global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: loki
    static_configs:
      - targets: [ "loki:3100" ]

  - job_name: alloy
    static_configs:
      - targets: [ "alloy:9080" ]

  - job_name: spring-boot
    scheme: http
    docker_sd_configs:
      - host: tcp://docker-socket-proxy:2375
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [ __meta_docker_container_label_metrics_scrape ]
        regex: true
        action: keep

      - source_labels: [ __meta_docker_container_label_metrics_path ]
        regex: (.+)
        target_label: __metrics_path__

      - source_labels: [ __meta_docker_container_label_com_docker_compose_service, __meta_docker_container_label_metrics_port ]
        regex: (.+);(.+)
        replacement: $1:$2
        target_label: __address__

      - source_labels: [ __meta_docker_container_label_com_docker_compose_service ]
        target_label: service

      - source_labels: [ __meta_docker_container_label_app ]
        target_label: app

      - source_labels: [ __address__ ]
        target_label: instance

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: [ 'node-exporter:9100' ]
